package com.test.fincti

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

/**
 * Represents a transaction entity in the database.
 *
 * @property id Unique identifier for the transaction, auto-generated by Room.
 * @property label Short description or name of the transaction (e.g., "Grocery").
 * @property amount The amount of money involved in the transaction. Positive for income, negative for expenses.
 * @property description Detailed description of the transaction (e.g., "Bought groceries at SuperMart").
 * @property type Indicates the type of transaction: "0" for expense, "1" for income.
 * @property category Category of the transaction (e.g., "Food", "Entertainment").
 * @property photo Optional field for storing an image related to the transaction as a ByteArray.
 */
@Entity(tableName = "transactions")
data class Transaction(
    @PrimaryKey(autoGenerate = true) val id: Int,
    val label: String,
    val amount: Double,
    val description: String,
    val type: String,
    val category: String,
    val photo: ByteArray? // Optional field for storing an image associated with the transaction
) : Serializable {
    // The Serializable interface allows instances of this class to be serialized and passed between activities or saved to disk.
}
